version: "3"

services:
  db:
    image: postgres:14
    restart: always
    ports:
            - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    volumes:
      - pgdata:/var/lib/postgresql/data/
  backend:
    build:
      context: ./backend
    restart: always
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 9009
    volumes:
      - ./backend:/code/
    ports:
      - "9009:9009"
    env_file:
      - ./backend/env_file
    depends_on:
      - db
volumes:
  pgdata:
